@kestrelPort = 7246
@iisPort = 44352
@baseUrl = https://localhost:{{kestrelPort}}

@policyId = 1
@nonExistentPolicyId = 100

### GetPolicy - 200

GET {{baseUrl}}/Policies/{{policyId}}

### GetPolicy - 404
GET {{baseUrl}}/Policies/{{nonExistentPolicyId}}

### GetPolicies - 200
GET {{baseUrl}}/Policies

### PostPolicies - 200
POST {{baseUrl}}/Policies
Content-Type: application/json

{
  "policyNumber": "12345",
  "premium": 50,
  "startDate": "2024-09-04T00:00:00.000Z"
}

### PostPolicies - 400
POST {{baseUrl}}/Policies
Content-Type: application/json

{
  "policyNumber": null,
  "premium": 50,
  "startDate": "2024-09-04T00:00:00.000Z"
}

### Export - 200
POST {{baseUrl}}/Policies/Export?startDate=2024-04-01&endDate=2024-09-04
